import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import DestinationCard from '../components/DestinationCard';
import { Sparkles, Map, Brain, Wallet,Smartphone, Backpack } from "lucide-react";
const Home = () => {
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    const handleScroll = () => setScrolled(window.scrollY > 50);
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const featuredDestinations = [
    {
      id: 1,
      name: 'Goa',
      state: 'Goa',
      image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600&h=400&fit=crop',
      description: 'Beautiful beaches, Portuguese heritage, and vibrant nightlife. Perfect for beach lovers and party enthusiasts.'
    },
    {
      id: 2,
      name: 'Manali',
      state: 'Himachal Pradesh',
      image: 'https://images.unsplash.com/photo-1580135776196-0d5376fe6d6e?w=600&h=400&fit=crop',
      description: 'Scenic hill station in the Himalayas with adventure sports, snow-capped mountains, and serene landscapes.'
    },
    {
      id: 3,
      name: 'Jaipur',
      state: 'Rajasthan',
      image: 'https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=600&h=400&fit=crop',
      description: 'The Pink City with magnificent forts, palaces, and rich cultural heritage. A royal experience awaits.'
    },
    {
      id: 4,
      name: 'Kerala',
      state: 'Kerala',
      image: 'https://images.unsplash.com/photo-1580519542036-c47de6196ba5?w=600&h=400&fit=crop',
      description: 'Backwaters, Ayurvedic treatments, and lush green landscapes. Experience God\'s Own Country.'
    }
  ];

 const features = [
  {
    icon: Brain,
    title: "AI-Powered Planning",
    description: "Create smart travel plans using advanced AI.",
    color: "from-purple-500 to-pink-600",
    glow: "rgba(168,85,247,0.35)"
  },
  {
    icon: Wallet,
    title: "Cost Estimation",
    description: "Get accurate budget estimates for your trips.",
    color: "from-green-500 to-emerald-600",
    glow: "rgba(16,185,129,0.35)"
  },
  {
    icon: Sparkles,
    title: "Smart Recommendations",
    description: "Receive personalized travel suggestions instantly.",
    color: "from-blue-500 to-indigo-600",
    glow: "rgba(59,130,246,0.35)"
  },
  {
    icon: Smartphone,
    title: "Mobile Friendly",
    description: "Plan and manage trips easily on any device.",
    color: "from-orange-500 to-red-500",
    glow: "rgba(249,115,22,0.35)"
  }
];

  // const stats = [
  //   { value: '500+', label: 'Destinations', description: 'Across Incredible India' },
  //   { value: '10K+', label: 'Itineraries', description: 'Generated by AI' },
  //   { value: '99%', label: 'Satisfaction', description: 'From happy travelers' },
  //   { value: '50K+', label: 'Happy Travelers', description: 'And counting' }
  // ];

  return (
    <div className="min-h-screen overflow-x-hidden">
      
      {/* ============================================================ */}
      {/* SECTION 1: HERO SECTION - Responsive */}
      {/* ============================================================ */}
      <section className="relative w-full overflow-hidden bg-gradient-to-br from-blue-900 via-purple-900 to-indigo-900">
        <div className="relative w-full min-h-[500px] sm:h-[550px] md:h-[600px] lg:h-[700px]">
          <div className="absolute inset-0 bg-gradient-to-t from-black/50 via-black/20 to-black/10"></div>
          
          <div className="absolute inset-0 z-20 flex flex-col items-center justify-center px-8 sm:px-6 py-0">
            <div className="flex flex-col items-center text-center max-w-5xl mx-auto">
              {/* Badge - Responsive */}
              <div className="inline-flex items-center gap-1.5 sm:gap-2 px-3 sm:px-4 py-1 sm:py-1.5 rounded-full bg-white/10 border border-white/25 backdrop-blur-md mb-4 sm:mb-6">
              
                <span className="w-1 h-1 sm:w-1.5 sm:h-1.5 rounded-full bg-green-400 animate-pulse"></span>
                
                <span className="font-semibold text-[10px] sm:text-xs uppercase tracking-wider text-white/90">AI-Powered Travel Planning</span>
              </div>
              
              {/* Heading - Responsive font sizes */}
              <h1 className="text-3xl sm:text-5xl md:text-6xl lg:text-7xl xl:text-8xl font-bold text-white tracking-tight mb-3 sm:mb-6">
                Discover
                <span className="block bg-gradient-to-r from-yellow-400 to-orange-400 bg-clip-text text-transparent mt-1 sm:mt-2">
                  Incredible India
                </span>
              </h1>
              
              {/* Description - Responsive */}
              <p className="text-sm sm:text-base md:text-lg lg:text-xl text-white/80 max-w-3xl mb-6 sm:mb-10 leading-relaxed px-2">
                Get complete personalized itineraries with costs, hotels, and local insights for every destination in India.
              </p>
              
              {/* Buttons - Responsive stacking */}
              <div className="flex flex-col sm:flex-row gap-3 sm:gap-4 justify-center w-full sm:w-auto px-4 sm:px-0">
                <Link to="/ai-assistant" className="w-full sm:w-auto">
                  <button className="group relative inline-flex items-center justify-center font-semibold transition-all duration-300 bg-orange-500 text-white hover:bg-orange-600 shadow-lg shadow-orange-500/30 px-4 sm:px-2 md:px-8 py-2.5 sm:py-2 md:py-4 rounded-full text-sm sm:text-base md:text-lg w-full">
                    <span className="relative z-10 flex items-center gap-2">
                       Start AI Trip Planning
                      <svg className="w-3 h-3 sm:w-4 sm:h-4 group-hover:translate-x-1 transition-transform" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                      </svg>
                    </span>
                  </button>
                </Link>
                <Link to="/dashboard" className="w-full sm:w-auto">
                  <button className="group relative inline-flex items-center justify-center font-semibold transition-all duration-300 bg-white/10 backdrop-blur-sm text-white hover:bg-white/20 border border-white/20 px-4 sm:px-6 md:px-8 py-2.5 sm:py-3 md:py-4 rounded-full text-sm sm:text-base md:text-lg w-full">
                    View My Trips
                  </button>
                </Link>
              </div>
            </div>
          </div>
        </div>

        {/* Scroll indicator - Hidden on mobile */}
        {/* <div className="absolute bottom-4 sm:bottom-8 left-1/2 transform -translate-x-1/2 animate-bounce z-20 hidden sm:block">
          <div className="w-5 h-8 sm:w-6 sm:h-10 border-2 border-white/50 rounded-full flex justify-center">
            <div className="w-1 h-1.5 sm:w-1 sm:h-2 bg-white/50 rounded-full mt-1.5 sm:mt-2"></div>
          </div>
        </div> */}
      </section>

      {/* ============================================================ */}
      {/* SECTION 2: STATS SECTION - Dark Futuristic & Responsive */}
      {/* ============================================================ */}
      {/* <section className="py-10 sm:py-12 md:py-16 lg:py-20 relative overflow-hidden bg-neutral-950">
    
        <div className="absolute inset-0 bg-gradient-to-r from-blue-950 via-purple-950 to-neutral-950"></div>
        
        Glowing Orbs - Hidden on mobile for performance
        <div className="hidden md:block absolute -top-32 -left-20 w-[500px] h-[500px] bg-blue-600/30 rounded-full blur-[120px] pointer-events-none animate-pulse"></div>
        <div className="hidden md:block absolute -bottom-32 -right-20 w-[500px] h-[500px] bg-purple-600/20 rounded-full blur-[120px] pointer-events-none animate-pulse delay-1000"></div>
        
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          Stats grid - Responsive: 2x2 on mobile, 4x1 on desktop
          <div className="grid grid-cols-2 md:flex md:flex-row items-center justify-center gap-6 sm:gap-8 md:gap-0">
            {stats.map((stat, index) => (
              <div key={index} className="flex items-center justify-center">
                <div className="flex flex-col items-center text-center px-2 sm:px-3 md:px-4 group cursor-pointer w-full">
                  <div className="relative">
                    <div className="absolute -inset-1 bg-gradient-to-r from-blue-500 to-purple-500 rounded-full blur-md opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>
                    <div className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl xl:text-6xl font-black bg-gradient-to-br from-white via-blue-100 to-purple-200 bg-clip-text text-transparent mb-1 sm:mb-2 drop-shadow-sm">
                      {stat.value}
                    </div>
                  </div>
                  <p className="font-semibold text-xs sm:text-sm md:text-base text-white/90 max-w-[10rem] sm:max-w-[12rem] mx-auto leading-tight sm:leading-snug">
                    {stat.label}
                  </p>
                  <p className="text-[10px] sm:text-xs text-white/50 mt-0.5 sm:mt-1">
                    {stat.description}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section> */}

      {/* ============================================================ */}
      {/* SECTION 3: FEATURES SECTION - Glassmorphism & Responsive */}
      {/* ============================================================ */}
      <div className="absolute inset-0 pointer-events-none overflow-hidden">

  <div className="absolute top-0 left-[10%] w-[500px] h-[500px] bg-blue-400/20 rounded-full blur-[120px]"></div>

  <div className="absolute bottom-0 right-[10%] w-[600px] h-[600px] bg-purple-400/20 rounded-full blur-[130px]"></div>

</div>
      <section className="relative py-12 sm:py-16 md:py-20 lg:py-28 overflow-hidden bg-neutral-50/50">
      <div className="absolute inset-0 pointer-events-none overflow-hidden">

  <div className="absolute top-0 left-[10%] w-[500px] h-[500px] bg-blue-400/20 rounded-full blur-[120px]"></div>

  <div className="absolute bottom-0 right-[10%] w-[600px] h-[600px] bg-purple-400/20 rounded-full blur-[130px]"></div>

</div>  
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          {/* Section Header - Responsive */}
          <div className="text-center mb-8 sm:mb-12 md:mb-16">
            
            <div className="inline-flex items-center gap-1.5 sm:gap-2 px-3 sm:px-4 py-1 sm:py-1.5 rounded-full bg-blue-50 border border-blue-100 mb-4 sm:mb-6">
              <div className="relative flex items-center justify-center w-2 h-2">
                <span className="absolute inline-flex w-full h-full rounded-full bg-primary-500 opacity-75 animate-ping" />
                <span className="w-1 h-1 sm:w-1.5 sm:h-1.5 rounded-full bg-blue-500" />
              </div>
              <span className="font-semibold text-[10px] sm:text-xs uppercase tracking-wider text-blue-700">
                Why Choose Us
              </span>
            </div>

            <h2 className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold text-gray-900 mb-2 sm:mb-4">
              Why Choose <span className="bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">TravelIndia?</span>
            </h2>
            <p className="text-sm sm:text-base md:text-lg text-gray-600 max-w-2xl mx-auto px-4">
              We combine artificial intelligence with local expertise to create perfect travel experiences
            </p>
          </div>

          {/* Features Grid - Responsive: 1x on mobile, 2x on tablet, 4x on desktop */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-5 md:gap-6">
  {features.map((feature, index) => (
  <div key={index} className="relative group h-full">

    {/* 🔥 OUTER GLOW BORDER */}
    <div className="absolute -inset-[2px] bg-gradient-to-r from-blue-500 via-purple-500 to-indigo-500 rounded-3xl blur-md opacity-0 group-hover:opacity-60 transition-opacity duration-500"></div>

    {/* 🧊 MAIN CARD */}
    <div className="relative h-full bg-white/85 backdrop-blur-xl px-6 py-8 rounded-3xl shadow-2xl border border-neutral-100 group-hover:border-transparent transition-all duration-300 flex flex-col items-center sm:items-start text-center sm:text-left gap-5 z-10">

      {/* ICON SECTION */}
      <div className="relative flex-shrink-0">

        {/* INNER GLOW */}
        <div 
          className="absolute inset-0 rounded-2xl blur-xl opacity-0 group-hover:opacity-80 transition-opacity duration-500 scale-110"
          style={{
            background: "rgba(99,102,241,0.35)" // you can customize per card later
          }}
        />

        {/* ICON BOX */}
        <div className={`relative w-20 h-20 rounded-2xl bg-gradient-to-br ${feature.color} flex items-center justify-center group-hover:-translate-y-1 group-hover:scale-105 transition-all duration-500 shadow-md overflow-hidden`}>
          
          {/* SHINE EFFECT */}
          <span className="absolute inset-0 bg-gradient-to-r from-transparent via-white/30 to-transparent -translate-x-full group-hover:translate-x-full transition-transform duration-700"></span>

         <div className={`w-20 h-20 rounded-2xl bg-gradient-to-br ${feature.color} flex items-center justify-center`}>

  <feature.icon className="w-6 h-6 sm:w-8 sm:h-8 md:w-10 md:h-10 text-white" />

</div>
        </div>
      </div>
 
      {/* TITLE */}
      <h4 className="font-bold text-lg text-neutral-900 mt-2 group-hover:text-blue-600 transition-colors duration-300">
        {feature.title}
      </h4>

      {/* DESCRIPTION */}
      <p className="text-neutral-600 text-sm leading-relaxed group-hover:text-neutral-700 transition-colors duration-300">
        {feature.description}
      </p>

      {/* CORNER DECOR */}
      <div className="absolute bottom-0 right-0 w-24 h-24 bg-gradient-to-tl from-gray-100 to-transparent rounded-tl-full opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>

    </div>
  </div>
))}
          </div>
        </div>
      </section>

      {/* ============================================================ */}
      {/* SECTION 4: FEATURED DESTINATIONS - Responsive */}
      {/* ============================================================ */}
      <section className="py-12 sm:py-16 md:py-20 lg:py-28 bg-gray-50">
        <div className="text-center mb-8 sm:mb-12 md:mb-16">
          
            <div className="inline-flex items-center gap-1.5 sm:gap-2 px-3 sm:px-4 py-1 sm:py-1.5 rounded-full bg-blue-50 border border-blue-100 mb-4 sm:mb-6">
              <div className="relative flex items-center justify-center w-2 h-2">
                <span className="absolute inline-flex w-full h-full rounded-full bg-primary-500 opacity-75 animate-ping" />
                <span className="w-1 h-1 sm:w-1.5 sm:h-1.5 rounded-full bg-blue-500" />
              </div>
              <span className="font-semibold text-[10px] sm:text-xs uppercase tracking-wider text-blue-700">
                START EXPLORING
              </span>
            </div>
          
          <div className="text-center mb-8 sm:mb-12 md:mb-16">
            <h2 className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold text-gray-900 mb-2 sm:mb-4">
              Featured <span className="bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">Destinations</span>
            </h2>
            <p className="text-sm sm:text-base md:text-lg text-gray-600 max-w-2xl mx-auto px-4">
              Explore the most beautiful places in India with our AI-powered travel planner
            </p>
          </div>

          {/* Destinations Grid - Responsive */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-5 md:gap-6">
            {featuredDestinations.map((destination) => (
              <DestinationCard key={destination.id} destination={destination} />
            ))}
          </div>

          {/* Button - Responsive */}
          <div className="text-center mt-8 sm:mt-10 md:mt-12">
            <Link to="/ai-assistant">
              <button className="px-5 sm:px-6 md:px-8 py-2.5 sm:py-3 md:py-4 rounded-full font-semibold text-sm sm:text-base md:text-lg text-white bg-gradient-to-r from-blue-600 to-purple-600 hover:shadow-lg hover:shadow-purple-500/25 transition-all duration-300">
                Explore All Destinations →
              </button>
            </Link>
          </div>
        </div>
      </section>

      {/* ============================================================ */}
      {/* SECTION 5: CTA SECTION - Responsive */}
      {/* ============================================================ */}
      <section className="relative py-12 sm:py-16 md:py-20 lg:py-28 overflow-hidden bg-gradient-to-r from-blue-600 to-purple-600">
        <div className="absolute inset-0 opacity-10">
          <div className="absolute top-0 left-0 w-48 h-48 sm:w-64 sm:h-64 md:w-96 md:h-96 bg-white rounded-full blur-[120px]"></div>
          <div className="absolute bottom-0 right-0 w-48 h-48 sm:w-64 sm:h-64 md:w-96 md:h-96 bg-white rounded-full blur-[120px]"></div>
        </div>
        <div className="relative z-10 max-w-4xl mx-auto text-center px-4 sm:px-6">
          <h2 className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold text-white mb-3 sm:mb-4 md:mb-6">
            Ready to Explore India?
          </h2>
          <p className="text-sm sm:text-base md:text-lg text-blue-100 mb-6 sm:mb-8 md:mb-10 max-w-2xl mx-auto px-4">
            Let our AI create the perfect itinerary for your next adventure. No destination is too remote!
          </p>
          <Link to="/ai-assistant">
            <button className="px-5 sm:px-6 md:px-8 py-2.5 sm:py-3 md:py-4 rounded-full font-semibold text-sm sm:text-base md:text-lg bg-white text-blue-600 hover:bg-gray-100 shadow-xl transition-all duration-300 hover:scale-105">
              🎯 Start Your AI Trip Plan
            </button>
          </Link>
        </div>
      </section>
      
    </div>
  );
};

export default Home;