import React from 'react';
import { Link } from 'react-router-dom';
import DestinationCard from '../components/DestinationCard';

const Home = () => {
  const featuredDestinations = [
    {
      id: 1,
      name: 'Goa',
      state: 'Goa',
      image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=400&h=300&fit=crop',
      description: 'Beautiful beaches, Portuguese heritage, and vibrant nightlife. Perfect for beach lovers and party enthusiasts.'
    },
    {
      id: 2,
      name: 'Manali',
      state: 'Himachal Pradesh',
      image: 'https://images.unsplash.com/photo-1580135776196-0d5376fe6d6e?w=400&h=300&fit=crop',
      description: 'Scenic hill station in the Himalayas with adventure sports, snow-capped mountains, and serene landscapes.'
    },
    {
      id: 3,
      name: 'Jaipur',
      state: 'Rajasthan',
      image: '/https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=400&h=300&fit=crop',
      description: 'The Pink City with magnificent forts, palaces, and rich cultural heritage. A royal experience awaits.'
    },
    {
      id: 4,
      name: 'Kerala',
      state: 'Kerala',
      image: '/https://images.unsplash.com/photo-1580519542036-c47de6196ba5?w=400&h=300&fit=crop',
      description: 'Backwaters, Ayurvedic treatments, and lush green landscapes. Experience God\'s Own Country.'
    }
  ];

  const features = [
    {
      icon: '🤖',
      title: 'AI-Powered Planning',
      description: 'Get personalized itineraries generated by advanced AI for any destination in India.'
    },
    {
      icon: '💰',
      title: 'Cost Estimation',
      description: 'Accurate budget planning with hotel, transport, and activity cost breakdowns.'
    },
    {
      icon: '🏨',
      title: 'Smart Recommendations',
      description: 'Best hotels, local food, and hidden gems recommended by our AI system.'
    },
    {
      icon: '📱',
      title: 'Mobile Friendly',
      description: 'Access your travel plans anywhere, anytime with our responsive design.'
    }
  ];

  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="relative h-screen flex items-center justify-center bg-gradient-to-br from-blue-600 via-purple-600 to-indigo-700">
        <div 
          className="absolute inset-0 bg-cover bg-center bg-no-repeat opacity-20"
          style={{
            backgroundImage: 'url("https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=1200")'
          }}
        ></div>
        
        <div className="relative z-10 text-center text-white max-w-6xl mx-auto px-4">
          <h1 className="text-5xl md:text-7xl font-bold mb-6 leading-tight">
            Discover
            <span className="block text-transparent bg-clip-text bg-gradient-to-r from-yellow-400 to-orange-400">
              Incredible India
            </span>
          </h1>
          <p className="text-xl md:text-2xl mb-8 opacity-90 max-w-3xl mx-auto leading-relaxed">
            AI-Powered Travel Planning for Every Destination in India. Get complete itineraries with costs, hotels, and local insights.
          </p>
          
          {/* CTA Buttons */}
          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center mb-12">
            <Link 
              to="/ai-assistant"
              className="bg-orange-500 text-white px-8 py-4 rounded-full hover:bg-orange-600 transition-all duration-300 font-semibold text-lg shadow-2xl transform hover:scale-105"
            >
              🚀 Start AI Trip Planning
            </Link>
            <Link 
              to="/dashboard"
              className="border-2 border-white text-white px-8 py-4 rounded-full hover:bg-white hover:text-blue-600 transition-all duration-300 font-semibold text-lg"
            >
              View My Trips
            </Link>
          </div>

          {/* Stats */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-2xl mx-auto">
            <div className="text-center">
              <div className="text-3xl font-bold">500+</div>
              <div className="text-blue-200">Destinations</div>
            </div>
            <div className="text-center">
              <div className="text-3xl font-bold">10K+</div>
              <div className="text-blue-200">Itineraries</div>
            </div>
            <div className="text-center">
              <div className="text-3xl font-bold">99%</div>
              <div className="text-blue-200">Satisfaction</div>
            </div>
          </div>
        </div>

        {/* Scroll indicator */}
        <div className="absolute bottom-8 left-1/2 transform -translate-x-1/2 animate-bounce">
          <div className="w-6 h-10 border-2 border-white rounded-full flex justify-center">
            <div className="w-1 h-3 bg-white rounded-full mt-2"></div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold text-gray-800 mb-4">
              Why Choose TravelIndia?
            </h2>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              We combine artificial intelligence with local expertise to create perfect travel experiences
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <div key={index} className="bg-white rounded-2xl p-8 shadow-lg hover:shadow-xl transition-all duration-300 group">
                <div className="text-4xl mb-4 group-hover:scale-110 transition-transform duration-300">
                  {feature.icon}
                </div>
                <h3 className="text-xl font-bold text-gray-800 mb-3">{feature.title}</h3>
                <p className="text-gray-600 leading-relaxed">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Featured Destinations */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold text-gray-800 mb-4">
              Featured Destinations
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Explore the most beautiful places in India with our AI-powered travel planner
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {featuredDestinations.map((destination) => (
              <DestinationCard key={destination.id} destination={destination} />
            ))}
          </div>

          <div className="text-center mt-12">
            <Link 
              to="/ai-assistant"
              className="inline-block bg-gradient-to-r from-blue-600 to-purple-600 text-white px-8 py-4 rounded-full hover:from-blue-700 hover:to-purple-700 transition-all duration-300 font-semibold text-lg"
            >
              Explore All Destinations
            </Link>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-to-r from-blue-600 to-purple-600">
        <div className="max-w-4xl mx-auto text-center px-4 sm:px-6 lg:px-8">
          <h2 className="text-4xl md:text-5xl font-bold text-white mb-6">
            Ready to Explore India?
          </h2>
          <p className="text-xl text-blue-100 mb-8 max-w-2xl mx-auto">
            Let our AI create the perfect itinerary for your next adventure. No destination is too remote!
          </p>
          <Link 
            to="/ai-assistant"
            className="inline-block bg-white text-blue-600 px-8 py-4 rounded-full hover:bg-gray-100 transition-all duration-300 font-semibold text-lg shadow-2xl transform hover:scale-105"
          >
            🎯 Start Your AI Trip Plan
          </Link>
        </div>
      </section>
    </div>
  );
};

export default Home;